// Created by iWeb 2.0.4 local-build-20100821

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({shadow_0:new IWShadow({blurRadius:4,offset:new IWPoint(1.4142,1.4142),color:'#000000',opacity:0.500000}),stroke_1:new IWStrokeParts([{rect:new IWRect(-1,1,2,111),url:'About_Us_files/stroke_8.png'},{rect:new IWRect(-1,-1,2,2),url:'About_Us_files/stroke_9.png'},{rect:new IWRect(1,-1,148,2),url:'About_Us_files/stroke_10.png'},{rect:new IWRect(149,-1,2,2),url:'About_Us_files/stroke_11.png'},{rect:new IWRect(149,1,2,111),url:'About_Us_files/stroke_12.png'},{rect:new IWRect(149,112,2,3),url:'About_Us_files/stroke_13.png'},{rect:new IWRect(1,112,148,3),url:'About_Us_files/stroke_14.png'},{rect:new IWRect(-1,112,2,3),url:'About_Us_files/stroke_15.png'}],new IWSize(150,113)),stroke_2:new IWStrokeParts([{rect:new IWRect(-1,1,2,98),url:'About_Us_files/stroke_16.png'},{rect:new IWRect(-1,-1,2,2),url:'About_Us_files/stroke_17.png'},{rect:new IWRect(1,-1,698,2),url:'About_Us_files/stroke_18.png'},{rect:new IWRect(699,-1,2,2),url:'About_Us_files/stroke_19.png'},{rect:new IWRect(699,1,2,98),url:'About_Us_files/stroke_20.png'},{rect:new IWRect(699,99,2,2),url:'About_Us_files/stroke_21.png'},{rect:new IWRect(1,99,698,2),url:'About_Us_files/stroke_22.png'},{rect:new IWRect(-1,99,2,2),url:'About_Us_files/stroke_23.png'}],new IWSize(700,100)),shadow_1:new IWShadow({blurRadius:4,offset:new IWPoint(1.4142,1.4142),color:'#000000',opacity:0.500000}),stroke_0:new IWStrokeParts([{rect:new IWRect(-1,1,2,118),url:'About_Us_files/stroke.png'},{rect:new IWRect(-1,-1,2,2),url:'About_Us_files/stroke_1.png'},{rect:new IWRect(1,-1,698,2),url:'About_Us_files/stroke_2.png'},{rect:new IWRect(699,-1,2,2),url:'About_Us_files/stroke_3.png'},{rect:new IWRect(699,1,2,118),url:'About_Us_files/stroke_4.png'},{rect:new IWRect(699,119,2,2),url:'About_Us_files/stroke_5.png'},{rect:new IWRect(1,119,698,2),url:'About_Us_files/stroke_6.png'},{rect:new IWRect(-1,119,2,2),url:'About_Us_files/stroke_7.png'}],new IWSize(700,120))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('About_Us_files/About_UsMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');adjustLineHeightIfTooBig('id8');adjustFontSizeIfTooBig('id8');adjustLineHeightIfTooBig('id9');adjustFontSizeIfTooBig('id9');adjustLineHeightIfTooBig('id10');adjustFontSizeIfTooBig('id10');adjustLineHeightIfTooBig('id11');adjustFontSizeIfTooBig('id11');adjustLineHeightIfTooBig('id12');adjustFontSizeIfTooBig('id12');adjustLineHeightIfTooBig('id13');adjustFontSizeIfTooBig('id13');adjustLineHeightIfTooBig('id14');adjustFontSizeIfTooBig('id14');adjustLineHeightIfTooBig('id15');adjustFontSizeIfTooBig('id15');adjustLineHeightIfTooBig('id16');adjustFontSizeIfTooBig('id16');adjustLineHeightIfTooBig('id17');adjustFontSizeIfTooBig('id17');adjustLineHeightIfTooBig('id18');adjustFontSizeIfTooBig('id18');adjustLineHeightIfTooBig('id19');adjustFontSizeIfTooBig('id19');Widget.onload();fixAllIEPNGs('Media/transparent.gif');applyEffects()}
function onPageUnload()
{Widget.onunload();}
